Sprint1/step1
sultanbayev/react-burger pull request #1
Opened 2021-07-20 00:15 UTC by sultanbayev

Сверстаны AppHeader, BurgerConstructor, BurgerIngredients по дизайну

2021-07-20 10:51 UTC, SmilingJey requested changes
Здравствуйте

Хорошая работа. Приложение начинает разрабатываться. Отлично, что интерфейс соответвует макету, хорошая декомпозиция на компоненты, проект  собирается, правильно используются компоненты из библиотеки.

Но есть несколько замечаний:

**Замечания которые необходимо будет исправить ,что бы сдать работы на следующем этапе:**

- используйте kebab-case ак же в названии файлов самих компонентов, а не только в названии папок и css файлов

- тег li не может вкладываться в другой тег li

- принято называть массивы существительными во множественном числе

- описание ингредиента ввиде PropTypes.object слишком общее, следует описать всю структуру объекта

**Места, в которых можно улучшить проект:**

- верстка по возможности должна вписываться в высоту браузера и отображаться без скрола http://prntscr.com/1dgxay1

- используйте для компонентов обертку React.memo для функциональных компонентов, которая позволяет сократить количество лишних рендеров и улучшить производительность

Например:

```
const SomeComponent = () => {
  return (
     ...........
  );
};

export default React.memo(SomeComponent);
```

Более подробное описание некоторых замечаний, а так же дополнительные места, где можно улучшить проект, отмечены в коде ниже:

2021-07-20 10:51 UTC, SmilingJey commented on src/components/app/App.tsx
> +    <React.Fragment>
**Можно лучше**

можно использовать сокращенную запись React.Fragment:
```
  return (
    <>
      <AppHeader />
      <Main />
    </>
  );
```

2021-07-20 10:51 UTC, SmilingJey commented on src/components/app-header/app-logo/AppLogo.tsx
> +        <a href="#" className={styles.logo}>
**Можно лучше**

лого должно быть ссылкой на главную `href="/"`

2021-07-20 10:51 UTC, SmilingJey commented on src/components/burger-constructor/component-list/ComponentList.tsx
> +                        <li key={component._id} className={styles.staffing}>
**Можно лучше**

обратите внимание, что в бургере может быть несколько одинаковых ингредиентов, поэтому использовать во втором спринте _id  для key не получится

2021-07-20 10:51 UTC, SmilingJey commented on src/components/burger-constructor/component-list/ComponentList.tsx
> +                    components.staffing.map(component =>
**Надо исправить**

тег li не может вкладываться в другой тег li. Нужно обернуть этот список тоже в ul, или сделать список без вложенности, убрав выше` <li className={styles.staffing_container}>`

2021-07-20 10:51 UTC, SmilingJey commented on src/components/burger-constructor/component-list/ComponentList.tsx
> +        staffing: PropTypes.arrayOf(PropTypes.object).isRequired
**Надо исправить**

- принято называть массивы существительными во множественном числе, используйте вместо staffing например ingredients

2021-07-20 10:51 UTC, SmilingJey commented on src/components/burger-constructor/component-list/ComponentList.tsx
> +        bun: PropTypes.object.isRequired,
**Надо исправить**

описание ингредиента ввиде PropTypes.object слишком общее, следует описать всю структуру объекта

Т.к. подобные пропсы со структурой ингредиента встречаются в нескольких компонентах следует вынести его в отдельный файл (можно создать файл prop-types.js в корне src ) и переиспользовать описание пропсов ингрединта

2021-07-20 10:51 UTC, SmilingJey commented on src/components/burger-constructor/BurgerConstructor.tsx
> +    const staffingPrice = components.staffing.reduce((total, component) => total + component.price, 0);
**Можно лучше**

вычисления следует обернуть в useMemo, что бы они выполнялись только при изменении данных, а не при каждом рендере

```
const price = useMemo(() => {
    const staffingPrice = components.staffing.reduce((total, component) => total + component.price, 0);
    const bunPrice = components.bun.price * 2;
    return staffingPrice + bunPrice
}, [components])
```

2021-07-20 10:51 UTC, SmilingJey commented on src/components/burger-ingredients/tab-bar/TabBar.tsx
> +
**Можно лучше**
при клике на соответвующий таб должен происходить скрол к нужному разделй в списке

Для этого можно задать каждому заголовку соотвующий id (или использовать refы) и вызывать scrollIntoView
Например:
```
  const setTab = (tab) => {
    setCurrent(tab);
    const element = document.getElementById(tab);
    if (element) element.scrollIntoView({ behavior: "smooth" });
  };
```
где заголовкам разделов заданы соответсвующие атрибуты id 

https://developer.mozilla.org/ru/docs/Web/API/Element/scrollIntoView

2021-07-20 10:51 UTC, SmilingJey commented on src/components/burger-ingredients/BurgerIngredients.tsx
> +                <IngredientGroup name="Булки" ingredients={ingredients.filter((ingredient) => ingredient.type === 'bun')} />
**Можно лучше**

используйте  useMemo, что бы фильтрация не вызывалась при каждом ренедере
Например:

```
const buns = useMemo(ingredients.filter((item) => item.type === 'buns'), [ingredients]);

return (
   ....................
)

2021-07-20 10:51 UTC, SmilingJey commented on src/components/main/Main.tsx
> +    const state = {
**Можно лучше**

- лучше дать другое имя переменной, имя state ассоциируется со стейтом компонента

- лучше вынести описание ингредиентов бургера в отдельный файл с данными, а не описывать данные в компоненте даже если это временное решение

2021-07-28 23:47 UTC, sultanbayev commented on src/components/app/App.tsx
> +    <React.Fragment>
сделано

2021-07-28 23:47 UTC, sultanbayev commented on src/components/app-header/app-logo/AppLogo.tsx
> +        <a href="#" className={styles.logo}>
сделано

2021-07-28 23:47 UTC, sultanbayev commented on src/components/burger-constructor/component-list/ComponentList.tsx
> +                        <li key={component._id} className={styles.staffing}>
заменено на индексы массива

2021-07-28 23:48 UTC, sultanbayev commented on src/components/burger-constructor/component-list/ComponentList.tsx
> +                    components.staffing.map(component =>
обернул в ul, теперь структура такая: ul>li>ul>li

2021-07-28 23:48 UTC, sultanbayev commented on src/components/burger-constructor/component-list/ComponentList.tsx
> +        staffing: PropTypes.arrayOf(PropTypes.object).isRequired
переименовано в ingredients

2021-07-28 23:49 UTC, sultanbayev commented on src/components/burger-constructor/component-list/ComponentList.tsx
> +        bun: PropTypes.object.isRequired,
вынесено в файл src/utils/prop-types.js

2021-07-28 23:49 UTC, sultanbayev commented on src/components/burger-constructor/BurgerConstructor.tsx
> +    const staffingPrice = components.staffing.reduce((total, component) => total + component.price, 0);
обернул в useMemo

2021-07-28 23:50 UTC, sultanbayev commented on src/components/burger-ingredients/tab-bar/TabBar.tsx
> +
прокрутка реализована

2021-07-28 23:50 UTC, sultanbayev commented on src/components/burger-ingredients/BurgerIngredients.tsx
> +                <IngredientGroup name="Булки" ingredients={ingredients.filter((ingredient) => ingredient.type === 'bun')} />
обернул в useMemo

2021-07-28 23:51 UTC, sultanbayev commented on src/components/main/Main.tsx
> +    const state = {
вынес в отдельный файл src/utils/components.js

2021-07-28 23:55 UTC, sultanbayev commented
Были исправлены моменты с замечаниями выше. А также:

- верстка по возможности должна вписываться в высоту браузера и отображаться без скрола http://prntscr.com/1dgxay1
не сделано, так как на мониторах с небольшой высотой (>=768px) конструктор не помещается, плохо смотрится и сложно пользоваться в итоге приложением.

- используйте для компонентов обертку React.memo для функциональных компонентов, которая позволяет сократить количество лишних рендеров и улучшить производительность
выполнено, обернул компоненты в React.memo

2021-07-29 17:42 UTC, irinamozes commented
Проект отличный!

Что, я думаю, надо подправить.

1. Как написано в Ваших лекциях https://praktikum.yandex.ru/learn/react/courses/b512c4ac-8797-4b96-935a-6b2865f27c9a/sprints/6021/topics/06c4d56c-b0fa-40ac-9345-79255d4aaa2a/lessons/1d53e9dc-c14a-4052-9d3f-c5ff15c82d8d/,
(раздел Списки в React) задаётся у первого элемента размётки элемента списка. Поэтому атрибут key (key={ingredient._id}) нужно задать у тега li, для компоненты  IngredientCard атрибут key можно не задавать.

Что можно лучше.

1. В HOC React.memo (https://praktikum.yandex.ru/learn/react/courses/b512c4ac-8797-4b96-935a-6b2865f27c9a/sprints/6021/topics/3daef531-37a0-4521-ac9c-dac879418335/lessons/1d29690a-33b0-4a1f-bac3-0967ddeedcc4/),
имеет смысл обёртывать только компоненты, имеющие пропсы, так как React.memo, решает нужно ли рендерить компоненту, проверяя изменились ли её текущие пропсы по сравнению с предыдущими, и рендерит компоненту только
в случае изменения, даже, если рендерится повторно родительская компонента. Также надо учитывать, что, если пропсы компоненты постоянно меняются, то рендер всё равно будет происходить, несмотря на то, что компонента обёрнута в React.memo, и тогда обёртка в React.memo будет только замедлять работу программы. Нужно стараться
не передавать компоненте лишних пропсов, которые могут меняться, а передавать только те, которые компоненте необходимы.

Задание принимается.

Желаю дальнейших успехов в учёбе и удачи!

2021-07-29 17:44 UTC, merged