Sprint1/step2
sultanbayev/react-burger pull request #2
Opened 2021-07-30 01:30 UTC by sultanbayev

Были созданы компоненты Modal и ModalOverlay. Созданы детали для модулей OrderDetails и IngredientDetails.

2021-07-30 19:43 UTC, AygulMalikova requested changes
Отличная работа! 

У вас хорошо структурированный и чистый код, разделенный на компоненты, весь необходимый функционал реализован и работает верно!

Но есть небольшие замечания. В первую очередь прошу вас обратить внимание на реализацию модального окна. Пожалуйста, добавьте пакет 'prop-types' в зависимости. И также, были оставлены другие комментарии и рекомендации по улучшению вашего кода.

Я напоминаю, что работа будет принята, как только все критические ошибки будут исправлены. Желаю вам удачи!

2021-07-30 19:43 UTC, AygulMalikova commented on src/components/app/app.js
> +  const url = 'https://norma.nomoreparties.space/api/ingredients';
Можно лучше:

Вы можете вынести данную константу в отдельный файл и разметить внутри utils

2021-07-30 19:43 UTC, AygulMalikova commented on src/components/app/app.js
> +        })
Надо исправить:

Важно также обрабатывать случай, когда запрос был неуспешен. Вы можете обратиться к данным статьям, чтобы подробнее изучить как это следует делать: 
https://developer.mozilla.org/ru/docs/Web/API/Fetch_API/Using_Fetch#%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0_%D1%83%D1%81%D0%BF%D0%B5%D1%88%D0%BD%D0%BE%D1%81%D1%82%D0%B8_%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%B0

https://learn.javascript.ru/promise-error-handling

2021-07-30 19:43 UTC, AygulMalikova commented on src/components/burger-constructor/burger-constructor.js
>  import ingredientShape from '../../utils/prop-types';
Надо исправить:

Пакет 'prop-types' отсутствует в ваших зависимостях. Пожалуйста, добавьте его

2021-07-30 19:43 UTC, AygulMalikova commented on src/components/modal/modal.js
> +            <ModalOverlay onModalClose={onModalClose}>
Надо исправить:

Обратите внимание на то, как реализовано модальное окно в примере из тренажера (https://practicum.yandex.ru/learn/react/courses/b512c4ac-8797-4b96-935a-6b2865f27c9a/sprints/6021/topics/3daef531-37a0-4521-ac9c-dac879418335/lessons/f60fe57f-6c77-446c-966d-1fefe0413a9f/). 

ModalOverlay — фоновая подложка под модальным окном, и она не принимает children (в примере этот компонент называется ModalBackDrop). Она должна принимать только функцию закрытия. Пожалуйста, реализуйте по примеру с теорией

2021-07-30 22:05 UTC, sultanbayev commented on src/components/app/app.js
> +  const url = 'https://norma.nomoreparties.space/api/ingredients';
вынес в файл constants.js

2021-07-30 22:09 UTC, sultanbayev commented on src/components/app/app.js
> +        })
обработано 
`.then(response => {
          if (!response.ok) throw new Error('Ошибка сети');
          response.json()
        })`

2021-07-30 22:14 UTC, sultanbayev commented on src/components/burger-constructor/burger-constructor.js
>  import ingredientShape from '../../utils/prop-types';
добавлено в зависимости `"prop-types": "^15.7.2",`

2021-07-30 22:29 UTC, sultanbayev commented on src/components/modal/modal.js
> +            <ModalOverlay onModalClose={onModalClose}>
fixed

2021-07-31 07:14 UTC, AygulMalikova commented
Ваша работа принята, я вас поздравляю! Все ошибки исправлены и все условия задания выполнены. У вас отличный код, поделенный на компоненты. Так держать! Еще раз поздравляю и желаю вам дальнейших успехов!

2021-07-31 17:09 UTC, merged